services:
  - type: web
    name: meili
    env: docker
    repo: https://github.com/EbenIOIO/meili.git
    plan: starter
    region: frankfurt
    disk:
      name: meili-data
      mountPath: /meili-data
      sizeGB: 10
    envVars:
      - key: MEILI_HTTP_ADDR
        value: 0.0.0.0:80
      - key: MEILI_MASTER_KEY
        generateValue: true
      - key: MEILI_DB_PATH
        value: /meili-data
      - key: MEILI_ENV
        value: development
    healthCheckPath: /healthz
    healthCheckTimeoutSeconds: 120
